services:
  todo-list-db:
    image: mongo:latest
    container_name: "todo-list-db"
    ports:
      - "27017:27017"
  todo-list-api:
    build: .
    image: todo-list-api
    container_name: "todo-list-api"
    ports:
      - "8080:8080"
    links:
      - todo-list-db
