services:
  mongodb:
    image: mongo
    container_name: todo-list-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: /data/mongodb
    ports:
      - "27017:27017"
    volumes:
      - db:/data/mongodb

networks:
  db:
    driver: bridge

volumes:
  db:
