spring:
  data:
    mongodb:
      uri: mongodb://todo-list-db:27017/todo-list
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <CLIENT_ID>
            clientSecret: <CLIENT_SECRET>
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google